/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    application
    `java-library`
}
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // ETCD
    implementation("io.etcd:jetcd-core:0.7.3")
    implementation("org.slf4j:slf4j-simple:2.0.3")
    implementation("io.netty:netty-resolver-dns-native-macos:4.1.84.Final:osx-aarch_64")

    implementation("com.google.code.gson:gson:2.10")
}

application {
    mainClass.set("it.unibo.ds.lab.consensus.client.Main")
}

tasks.getByName<JavaExec>("run") {
    standardInput = System.`in`
    if (project.hasProperty("mode")) {
        when (project.property("mode").toString().toLowerCase()) {
            "uppercase", "u" -> args("-u")
            "lowercase", "l" -> args("-l")
        }
    }
}